### ISSUE TITLE
Using with Typescript

### ISSUE THREAD

**Issue by coffeepostal** [jesseskinner/svelte-autosize#1]
Hello, I'm learning Svelte/Typescript, and wanted to use your module, and it works great on a Svelte build without Typescript, but when I tried using it with Typescript, I got an error that a Google/Stackoverflow search said was a types issue and I had to run `npm i -D @types/svelte-autosize`.

So I did, and it's not in the registry. It still works, but it throws an error in VSCode, but you can get by the error if you add `declare module 'svelte-autosize';` to the `app.d.ts` file.

I'm not sure if this is hacky, or just the best way to do it, but I thought I'd mention it incase you want to add something about it in your README.

**Comment by jesseskinner** [comment]
Thanks for bringing this to my attention! I don't know enough about Typescript to know how to solve it, but I'll leave this issue here in case others are looking for a solution, or in case someone wants to submit a pull request that adds whatever it is Typescript is looking for here.

**Comment by ys-chung** [comment]
Hi, this is the typings I used for this module:

```typescript
declare module "svelte-autosize" {
	import type { Action } from "svelte/action"

	export default Action<HTMLElement>
}
```

**Comment by taishi55** [comment]
@ys-chung how did you paste it inside 
```
declare namespace App {
	// interface Locals {}
	// interface PageData {}
	// interface Error {}
	// interface Platform {}
}
```

**Comment by junwen-k** [comment]
It would be fantastic for this library to include declaration files for Typescript project. :)

**Comment by jesseskinner** [comment]
@junwen-k feel free to make a pull request to add this in. Thanks!

**Comment by jesseskinner** [comment]
Just a heads up that I believe v1.1.5 gets the types right once and for all. Please let me know if you have any further issues. Thanks @jachewz @junwen-k @ys-chung @taishi55 and @coffeepostal for your help!
