### ISSUE TITLE
Bug: no resize after external value change

### ISSUE THREAD

**Issue by FritzTheBat** [jesseskinner/svelte-autosize#3]
There's a small bug, that occurs when the textareas bind:value changes independently from the textarea, say when we want to clear user input after form is submitted. In these cases the target element stays enlarged even though its empty.

**Comment by jesseskinner** [comment]
@FritzTheBat Thanks for the issue. Is the example in the README helpful for working around this, ie. calling autosize.update after you clear user input?

```
<script>
import {tick} from 'svelte';
import autosize from 'svelte-autosize';

let textarea;
let value = '';
	
async function reset() {
  value = '';
  await tick();
  autosize.update(textarea);
}
</script>

<textarea use:autosize bind:this={textarea} bind:value></textarea>
<button on:click={reset}>Reset</button>
```

**Comment by jesseskinner** [comment]
@FritzTheBat If you're using SvelteKit with `use:enhance`, for example, you could probably do something like this:

```
use:enhance={() => async ({ update }) => {
  await update();
  // await tick(); might be necessary? not sure
  autosize.update(textarea);
}}
```
