### ISSUE TITLE
"default" is imported from external module "svelte-autosize" but never used

### ISSUE THREAD

**Issue by applemate** [jesseskinner/svelte-autosize#5]
I got this warning

"default" is imported from external module "svelte-autosize" but never used in....

**Comment by jesseskinner** [comment]
@craigcosmo are you maybe importing 'svelte-autosize' but not using it?

**Comment by applemate** [comment]
```js
<script lang="ts">
import autosize from 'svelte-autosize'
</script>

<textarea use:autosize></textarea>
```

this is the code

**Comment by jesseskinner** [comment]
@craigcosmo that's weird, but not something I can fix here unfortunately. I see you opened a ticket [here](https://github.com/sveltejs/svelte/issues/13122) so hopefully it can be resolved in the Svelte toolchain.

Maybe a workaround would be to "use" the import in another way, eg. something dumb like this?

```html
<script lang="ts">
import autosize from 'svelte-autosize';

autosize;
</script>

<textarea use:autosize></textarea>
```
