### ISSUE TITLE
TS support? getting `Property 'update' does not exist on type 'Action<HTMLElement, undefined, Record<never, any>>'.ts(2339)`

### ISSUE THREAD

**Issue by jstjoe** [jesseskinner/svelte-autosize#7]
Hello, thank you for building this!

I've got it implemented and the functionality is working in development, but I'm getting this TypeScript warning in VSCode.

```
Property 'update' does not exist on type 'Action<HTMLElement, undefined, Record<never, any>>'.ts(2339)
```

I also set ts-ignore on the import (I think) but still see the above warning. I noticed you added TS definitions (thank you!) but I think you'll need to extend the type to include the update method? I'm far from a professional though so this may just be user error.

Thanks again!

**Comment by jesseskinner** [comment]
Thanks for the feedback @jstjoe, you're absolutely right.

I think we could use [@types/autosize](https://www.npmjs.com/package/@types/autosize) and integrate those definitions here.

Happy to accept a pull request on this, or I'll get around to it sometime soon hopefully.

**Comment by jesseskinner** [comment]
@jstjoe it took a few iterations but I think it's working quite well now with v1.1.5. Let me know how it goes and thanks for creating the issue!
